[dependencies]
bulletproofs = "0.7"
curve25519-dalek = "3.1"
rand = "0.8"
bellman = "0.9"
pairing = "0.21"
distaff = { git = "https://github.com/GaloisInc/distaff", branch = "main" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
warp = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
blake3 = "1.2"
bincode = "1.3"



